# Generated by Django 4.1.1 on 2022-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_links_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='links',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
